### ISSUE TITLE
missing documentation link to org

### ISSUE THREAD

**Issue by polly73** [terraform-cisco-modules/easy-imm#1]
hi there i dont get this to run in our lab and it seems i miss a point here, how to try out this code. It seems i miss the org definition, but i cannot find, where i have to do that

│   on .terraform/modules/policies/locals.tf line 1160, in locals:
│ 1160:         name = "${local.npfx[org].port}${element(v.names, x)}${local.nsfx[org].port}"
│     ├────────────────
│     │ local.npfx is object with 6 attributes

**Comment by scotttyso** [comment]
@polly73 - when you first run the script what are the existing orgs in the Intersight account?  And what is your YAML configuration top level object (i.e. Organization) for your port policy? 

I wish it gave more details with the error messages like this but the top-level objects under npfx are the organization names.  So, the first part of the script pulls in all organization objects in Intersight.  When you first run the script, you should see something similar to this.

```
Changes to Outputs:
  + orgs  = {
      + Asgard  = "5f6509326972652d32fa70a8"
      + RICH    = "639ffbbe6972652d3243d65f"
      + Wakanda = "60aeca786972652d32ee5e46"
      + common  = "6505cc486972653201c3bc8a"
      + default = "5ddea1e16972652d32b6493a"
    }
  + pools = {}

```

My guess is within your `policies/` folder the org defined doesn't exist in your account. i.e. if your port policy was something like this:

```
---
#====================================
#   Policies -> Port - Variables
#====================================
blah:
  policies:
    port:
      - device_model: UCS-FI-6454
        names:
          - r143e-1-a
          - r143e-1-b
        port_channel_ethernet_uplinks:
          - admin_speed: Auto
            ethernet_network_group_policy: aci-uplink
            flow_control_policy: flow-ctrl
            interfaces:
              - port_id: 53
              - port_id: 54
            link_aggregation_policy: link-agg
            link_control_policy: link-ctrl
            pc_ids:
              - 53
              - 53
        port_channel_fc_uplinks:
          - admin_speed: 32Gbps
            interfaces:
              - port_id: 1
              - port_id: 2
            pc_ids:
              - 1
              - 1
            vsan_ids:
              - 100
              - 200
        port_modes:
          - custom_mode: FibreChannel
            port_list:
              - 1
              - 8
        port_role_servers:
          - port_list: 37,38
```

Note that `blah` isn't an existing organization from the output above.  It would need to be `Asgard, RICH, Wakanda, common, or default`, if this was running against my own Intersight account.

With the configuration above I would get the exact error message you are running into.

```
│ Error: Invalid index
│
│   on .terraform/modules/policies/locals.tf line 1160, in locals:
│ 1160:         name = "${local.npfx[org].port}${element(v.names, x)}${local.nsfx[org].port}"
│     ├────────────────
│     │ local.npfx is object with 5 attributes
│
│ The given key does not identify an element in this collection value.
```
